ALTER TABLE R_REALTIME_TASK
ADD TERMINAL_PROTOCOL VARCHAR2(2) DEFAULT '0';

ALTER TABLE R_REALTIME_TASK
ADD METER_PROTOCOL VARCHAR2(2) DEFAULT '0';

-- Add comments to the columns 
comment on column R_REALTIME_TASK.TERMINAL_PROTOCOL
  is '终端规约：0：376；1：浙规；';

comment on column R_REALTIME_TASK.METER_PROTOCOL
  is '表计（保护器）规约：0：645（97）；1：645（07）；2：浙规；5：QLLB；6：HDLB';
